executor: slurm
latency-wait: 30

default-resources:
  runtime: 150m
  slurm_partition: workstations

set-resources:
  kaiju_classify:
    slurm_partition: assemblix
    nodelist: assemblix2025
    mem_mb: 64000
    runtime: 150m

  kaiju_report:
    slurm_partition: assemblix
    mem_mb: 20000
    runtime: 150m
